### ISSUE TITLE
Error => Resolve The Issue

### ISSUE THREAD

**Issue by MeanMachine123** [the-Infected-Drake/TIDoS-Framework#6]
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 3, in <module>
    from google import search
ImportError: cannot import name search

**Comment by the-Infected-Drake** [comment]
### (Solved) ImportError: cannot import name search
I think I figured out your problem.
Please run the `uninstall.py` script to completely remove the program and then the `setup.py` script again so that all the dependencies are resolved. 

`search` is a module available within `google` in Python. So if the aforesaid still doesn't work, try installing `google` manually with this command -
    `   pip install google   `

Let me know if you get any errors in future.

 

> Goodluck

 **  - @_tID**

**Comment by MeanMachine123** [comment]
/TIDoS-Framework# pip install google
Requirement already satisfied: google in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from google)


pip install google


SAME RESULT.............



/TIDoS-Framework# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 3, in <module>
    from google import search


________________________________

**Comment by the-Infected-Drake** [comment]
Try running `pip install --upgrade --force-reinstall google` and let me know the result. If the error still persists, then it might be the case where your pip isn't carrying out the commands properly.

  You can try running `apt-get install --reinstall python-pip` so that everything runs fine with the pip setup. The next step would be to run the `setup.py` file and then try out the whole process.

Let me know if you are still facing problems.
@_tID

**Comment by MeanMachine123** [comment]
I have tried pip install search_google but all in vain


Again same Issue :>

~# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 3, in <module>
    from google import search
ImportError: cannot import name search





________________________________

**Comment by the-Infected-Drake** [comment]
I think a small bit of my code is causing the trouble.  Lemme remodify the code once.

- **@_tID**

**Comment by the-Infected-Drake** [comment]
I have edited the code that was causing the trouble. Now it should work good. Thanks for your issuance of the issue 😆. Please run the `uninstall.py` file and try a new clone of the repository. 

Thanks...
**- @_tID**

**Comment by MeanMachine123** [comment]
It is now working all fine.Really grateful to you for your response 😊RESOLVED NOW :)

________________________________

**Comment by tugdualnicolas** [comment]
Hi i have tried everything you said and i still have the error

Output of `tidos`: (Same result as root)
```
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 12, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google

```

**Comment by onlysubas** [comment]
Even after your updated code, it shows the same error...

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 15, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 2, in <module>
    import google
ImportError: No module named google

Help would me much appreciated
